#
# Makefile for TRIPS IM
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Sep 2003
# Time-stamp: <Mon Jan 19 14:17:33 EST 2004 ferguson>
#

NAME = IM
DEFSYS = defsys.lisp
SYSTEM = :im

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
