(in-package :im)

(setq test1
     '
	    (NEW-SPEECH-ACT
			    (UTT :TYPE UTT :SPEAKER :USER :ROOT V12027 :TERMS
				 ((TERM :LF (SPEECHACT V12027 SA_TELL :CONTENT V11755) :VAR V12027 :SEM <?>
     :INPUT (I WANT TO BUY A LAPTOP COMPUTER))
    (TERM :LF
     (F V11755 (:* ONT::WANT WANT) :ACTION V11820 :EXPERIENCER V11522 :TMA
      ((TENSE PRES)))
     :VAR V11755 :SEM
     ($ FT_SITUATION
      ((ASPECT F::INDIV-LEVEL) (TIME-SPAN F::EXTENDED) (CAUSE F::MENTAL)
       (LOCATIVE F::ANY-LOCATIVE) (TYPE F::EVENTUALITY) (CONTAINER -)
       (INFORMATION F::PROPOSITION) (INTENTIONAL -) (TRAJECTORY -)))
     :INPUT (I WANT TO BUY A LAPTOP COMPUTER))
    (TERM :LF (PRO V11522 (:* ONT::PERSON I) :PROFORM (I)) :VAR V11522 :SEM
     ($ FT_PHYS-OBJ
      ((OBJECT-FUNCTION F::OCCUPATION) (ORIGIN F::HUMAN) (FORM F::SOLID-OBJECT)
       (MOBILITY F::NON-SELF-MOVING) (GROUP -)
       (SPATIAL-ABSTRACTION F::SPATIAL-POINT) (TYPE F::ANY-TYPE) (KR-TYPE PERSON)
       (CONTAINER -) (INFORMATION -) (INTENTIONAL +) (TRAJECTORY -)))
     :INPUT (I))
    (TERM :LF (F V11820 (:* ONT::BUY BUY) :THEME V11891 :AGENT V11522) :VAR
     V11820 :SEM
     ($ FT_SITUATION
      ((ASPECT F::BOUNDED) (TIME-SPAN F::ATOMIC) (CAUSE F::AGENTIVE)
       (LOCATIVE F::ANY-LOCATIVE) (TYPE F::EVENTUALITY) (CONTAINER -)
       (INFORMATION F::PROPOSITION) (INTENTIONAL -) (TRAJECTORY -)))
     :INPUT (TO BUY A LAPTOP COMPUTER))
    (TERM :LF (A V11891 (:* ONT::COMPUTER COMPUTER) :ASSOC-WITH (V11886)) :VAR
     V11891 :SEM
     ($ FT_PHYS-OBJ
      ((OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION) (ORIGIN F::ARTIFACT)
       (FORM F::SOLID-OBJECT) (MOBILITY F::ANY-MOBILITY) (GROUP -)
       (SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION))
       (TYPE F::ANY-TYPE) (CONTAINER -) (INFORMATION -) (INTENTIONAL -)
       (TRAJECTORY -)))
     :INPUT (A LAPTOP COMPUTER))
    (TERM :LF (KIND V11886 (:* ONT::COMPUTER LAPTOP)) :VAR V11886 :SEM
     ($ FT_PHYS-OBJ
      ((OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION) (ORIGIN F::ARTIFACT)
       (FORM F::SOLID-OBJECT) (MOBILITY F::ANY-MOBILITY) (GROUP -)
       (SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION))
       (TYPE F::ANY-TYPE) (CONTAINER -) (INFORMATION -) (INTENTIONAL -)
       (TRAJECTORY -))))))
  :SYNTAX
  ((UTT :FEATS ((INPUT (I WANT TO BUY A LAPTOP COMPUTER)) (VAR V12027)) :SUB
    ((S :FEATS ((VAR V11755)) :SUB
      ((NP :FEATS ((VAR V11522)) :SUB ((PRO :FEATS ((VAR V11522) (INPUT I)))))
       (VP :FEATS ((VAR V11755)) :SUB
        ((VP- :FEATS ((VAR V11755)) :SUB
          ((V :FEATS ((VAR V11755) (INPUT WANT)))
           (CP :FEATS ((VAR V11820)) :SUB
            ((INFINITIVAL-TO :FEATS ((VAR V11806) (INPUT TO)))
             (VP :FEATS ((VAR V11820)) :SUB
              ((VP- :FEATS ((VAR V11820)) :SUB
                ((V :FEATS ((VAR V11820) (INPUT BUY)))
                 (NP :FEATS ((VAR V11891)) :SUB
                  ((SPEC :FEATS ((VAR V11846)) :SUB
                    ((DET :FEATS ((VAR V11846)) :SUB
                      ((ART :FEATS ((VAR V11846) (INPUT A)))))))
                   (N1 :FEATS ((VAR V11891)) :SUB
                    ((N1 :FEATS ((VAR V11886)) :SUB
                      ((N :FEATS ((VAR V11886) (INPUT LAPTOP)))))
                     (N1 :FEATS ((VAR V11891)) :SUB
                      ((N :FEATS
                        ((VAR V11891) (INPUT COMPUTER))))))))))))))))))))))))))

(setq test2
      '(new-speech-act (UTT :TYPE UTT :SPEAKER :USER :ROOT V7050 :TERMS
			    ((TERM :LF (SPEECHACT V7050 ONT::SA_REQUEST :CONTENT V6031))
			     (TERM :LF (F V6031 (:* ONT::REMOVING TAKE) :THEME V6349 :AGENT V6779))
			     (TERM :LF (IMPRO V6779 ONT::PERSON :PROFORM *YOU*))
			     (TERM :LF (A V6349 (:* ONT::PICTURE PICTURE) :ONT::OF V6667))
			     (TERM :LF (IMPRO V6667 (<OR> ONT::PHYS-OBJECT ONT::REFERENTIAL-SEM)))))))

(setq *test3*
      '(NEW-SPEECH-ACT (COMPOUND-COMMUNICATION-ACT :ACTS ((UTT :TYPE UTT :SPEAKER :USER :ROOT V6128 :TERMS ((TERM :LF (SPEECHACT V6128 ONT::SA_IDENTIFY :CONTENT V5855) :VAR V6128 :SEM <?> :INPUT (I)) (TERM :LF (PRO V5855 (:* ONT::PERSON I) :PROFORM (I)) :VAR V5855 :SEM ($ FT_PHYS-OBJ ((OBJECT-FUNCTION F::OCCUPATION) (ORIGIN F::HUMAN) (FORM F::SOLID-OBJECT) (MOBILITY F::ANY-MOBILITY) (GROUP -) (SPATIAL-ABSTRACTION F::SPATIAL-POINT) (TYPE F::ANY-TYPE) (TRAJECTORY -) (CONTAINER -) (INFORMATION -) (INTENTIONAL +))) :INPUT (I)))) (UTT :TYPE UTT :SPEAKER :USER :ROOT V6199 :TERMS ((TERM :LF (SPEECHACT V6199 ONt::SA_YN-QUESTION :CONTENT V6070) :VAR V6199 :SEM <?> :INPUT (WILL EIGHT)) (TERM :LF (F V6070 (:* ONT::ELLIPSIS) :THEME V6080 :TMA ((TENSE FUT) (MODALITY (:* ONT::FUTURE WILL)))) :VAR V6070 :SEM ($ FT_SITUATION ((ASPECT F::ANY-ASPECT) (TIME-SPAN F::ANY-TIME-SPAN) (CAUSE F::ANY-CAUSE) (LOCATIVE F::ANY-LOCATIVE) (TYPE F::EVENTUALITY) (TRAJECTORY -) (CONTAINER -) (INFORMATION F::PROPOSITION) (INTENTIONAL -))) :INPUT (WILL EIGHT)) (TERM :LF (THE V6080 ONT::TIME-LOC :AM-PM <?> :HOUR 8) :VAR V6080 :SEM ($ FT_TIME ((TIME-FUNCTION F::CLOCK-TIME) (SCALE POINT) (INFORMATION -) (INTENTIONAL -))) :INPUT (EIGHT)))) (UTT :TYPE UTT :SPEAKER :USER :ROOT V6141 :TERMS ((TERM :LF (SPEECHACT V6141 ont::SA_IDENTIFY :CONTENT V6090) :VAR V6141 :SEM <?> :INPUT (THE COMPUTER)) (TERM :LF (THE V6090 (:* ONT::COMPUTER COMPUTER)) :VAR V6090 :SEM ($ FT_PHYS-OBJ ((OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION) (ORIGIN F::ARTIFACT) (FORM F::SOLID-OBJECT) (MOBILITY F::ANY-MOBILITY) (GROUP -) (SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION)) (TYPE F::ANY-TYPE) (TRAJECTORY -) (CONTAINER -) (INFORMATION -) (INTENTIONAL -))) :INPUT (THE COMPUTER))))))))

(setq *dc-reply* ' (TELL :RECEIVER IM :IN-REPLY-TO PA13885 :CONTENT
    (ANSWER-RESOLVE-UTTERANCE :TERMS
     ((ANSWER :VAR V13842 :SCORE 1.0 :VALUES NIL)
      (ANSWER :VAR V12170 :SCORE 1.0 :VALUES NIL)
      (ANSWER :VAR V11425 :SCORE 1.0 :VALUES
       ((VALUE :SPEC
         (PRO V11425 (AND (TYPE V11425 PERSON) (PROFORM V11425 I)))
:SCORE
         0.8)))
      (ANSWER :VAR V12373 :SCORE 1.0 :VALUES NIL)
      (ANSWER :VAR V12573 :SCORE 1.0 :VALUES
       ((VALUE :SPEC (A V12573 (TYPE V12573 NIL)) :SCORE 0.8)))))
    :SENDER DISCOURSECONTEXT))
