#
# Makefile for Logging
#
# George Ferguson, ferguson@cs.rochester.edu, 17 Aug 1999
# $Id: Makefile,v 1.1.1.1 2005/01/14 19:48:08 ferguson Exp $
#

NAME = Logging
DEFSYS = defsys.lisp
SYSTEM = :logging

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/lib.mk
