#
# Makefile for Lexicon Manager
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Mar 2000
# $Id: Makefile,v 1.3 2005/08/04 17:21:04 ferguson Exp $
#

NAME = LexiconManager
DEFSYS = defsys.lisp
SYSTEM = :lxm

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
