#
# Makefile for Lexicon Manager
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Mar 2000
# $Id: Makefile,v 1.5 2017/12/21 02:22:48 wdebeaum Exp $
#

NAME = LexiconManager
DEFSYS = defsys.lisp
SYSTEM = :lxm

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
