#
# Makefile for Comm
#
# George Ferguson, ferguson@cs.rochester.edu, 13 Dec 1995
# $Id: Makefile,v 1.1.1.1 2005/01/14 19:48:14 ferguson Exp $
#

NAME = Comm
DEFSYS = defsys.lisp
SYSTEM = :comm

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/lib.mk

