#
# Makefile for SimpleKB
#
# George Ferguson, ferguson@cs.rochester.edu, 9 Feb 2004
# Time-stamp: <Mon Feb  9 14:12:24 EST 2004 ferguson>
#

NAME  = SimpleKB
DEFSYS = defsys.lisp
SYSTEM = :simplekb

CONFIGDIR = ../config
include $(CONFIGDIR)/lisp/lib.mk
