#
# Makefile for Ontology Manager
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Mar 2000
# $Id: Makefile,v 1.3 2005/08/04 17:21:03 ferguson Exp $
#

NAME = OntologyManager
DEFSYS = defsys.lisp
SYSTEM = :om

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
