
(define-words :pos W::v :templ AGENT-THEME-XP-TEMPL
 :words (
  (W::STOP
   (wordfeats (W::morph (:forms (-vb) :nom w::stop)))
   (SENSES
    ((EXAMPLE "He stopped the rioting")
     (LF-PARENT ONT::STOP)
     (SEM (F::Aspect F::bounded) (F::Time-span F::atomic))
     (templ cause-effect-xp-templ (xp (% w::vp (w::vform w::ing))))
     )
    ((EXAMPLE "he/the truck stopped")
     (LF-PARENT ONT::STOP)
     (SEM (F::Aspect F::bounded) (F::Time-span F::atomic))
     (templ affected-templ)
     (meta-data :origin fruit-carts :entry-date 20050308 :change-date nil :comments nil)
     )
    ((LF-PARENT ONT::STOP)
     (example "the computers/managers stopped working")
     (SEM (F::Aspect F::bounded) (F::Time-span F::atomic))
     (TEMPL affected-effect-xp-templ (xp (% w::vp (w::vform w::ing))))
     )
    ((LF-PARENT ONT::STOP)
     (SEM (F::Aspect F::bounded) (F::Time-span F::atomic))
     (TEMPL CAUSE-affected-xp-TEMPL)
     (EXAMPLE "He/The storm stopped the fair/the truck")
     )
    ((LF-PARENT ONT::STOP)
     (SEM (F::Aspect F::bounded) (F::Time-span F::atomic))
     (TEMPL effect-TEMPL)
     (EXAMPLE "The rioting stopped")
     )
     ((meta-data :origin wordnet-3.0 :entry-date 20090528 :change-date nil :comments nil)
     (LF-PARENT ONT::stop)
     (TEMPL CAUSE-EFFECT-AFFECTED-OBJCONTROL-TEMPL (xp (% w::cp (w::ctype w::s-from-ing))))
     (example "The hospital stops visitors from smoking")
     )
    )
   )
))
