
(define-list-of-words :pos W::n
  :senses (
	   ((LF-PARENT ONT::SALTWATER-fish)
	    (TEMPL COUNT-PRED-TEMPL)
	    )
	   )
  :words ( W::COD W::MENHADEN W::HERRING W::SARDINE W::ANCHOVY W::BLUEFISH W::BUTTERFISH w::croaker W::CUSK W::DOLPHINFISH W::FLATFISH W::FLOUNDER W::SOLE W::GROUPER W::HADDOCK W::HALIBUT W::LINGCOD W::MACKEREL (W::JACK W::MACKEREL) (W::KING W::MACKEREL) (W::SPANISH W::MACKEREL) W::MILKFISH W::MONKFISH W::MULLET (W::STRIPED W::MULLET) (W::OCEAN W::PERCH) (W::ATLANTIC W::OCEAN W::PERCH) W::POUT (W::OCEAN W::POUT) W::POLLOCK (W::WALLEYE W::POLLOCK) (W::FLORIDA W::POMPANO) W::ROCKFISH W::ROUGHY (W::ORANGE W::ROUGHY) W::SABLEFISH W::SCUP (W::SEA W::BASS) W::SEATROUT W::SHARK W::SHEEPSHEAD W::SNAPPER W::SUNFISH W::SWORDFISH W::TILEFISH W::TUNA  (W::BLUEFIN W::TUNA) (W::SKIPJACK W::TUNA) (W::YELLOWFIN W::TUNA) W::TURBOT (W::EUROPEAN W::TURBOT) W::WHITING W::WOLFFISH  W::YELLOWTAIL W::BLACKFISH W::DEVILFISH W::HERRING (W::SEA W::CUCUMBER) W::WHITEFISH W::JELLYFISH))
