#
# Makefile for Parser
#
# George Ferguson, ferguson@cs.rochester.edu, 13 Dec 1995
# $Id: Makefile,v 1.3 2005/08/04 17:21:03 ferguson Exp $
#

NAME = Parser
DEFSYS = defsys.lisp
SYSTEM = :parser

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
