#
# Makefile for defcomponent/io
#
# George Ferguson, ferguson@cs.rochester.edu, 13 Dec 1995
# $Id: Makefile,v 1.1.1.1 2005/01/14 19:48:13 ferguson Exp $
#

NAME = io
DEFSYS = defsys.lisp
SYSTEM = :io

CONFIGDIR=../../config
include $(CONFIGDIR)/lisp/lib.mk

