#
# Makefile for ChannelKB
#
# George Ferguson, ferguson@cs.rochester.edu, 9 Feb 2004
# Time-stamp: <Mon Feb  9 14:40:02 EST 2004 ferguson>
#

NAME  = ChannelKB
DEFSYS = defsys.lisp
SYSTEM = :channelkb

CONFIGDIR = ../config
include $(CONFIGDIR)/lisp/prog.mk
