PACKAGE = TRIPS.util.cwc

SRCS =	Args.java \
	CWCException.java \
	InvalidArgument.java \
	JavaFXApp.java \
	JavaFXWindowManager.java \
	MissingArgument.java \
	StandardCWCModule.java \
	SwingWindowManager.java \
	UnknownAction.java \
	UnknownObject.java \
	WindowConfig.java \
	WindowManager.java

CLASSES = $(SRCS:.java=.class) \
	JavaFXApp$$1.class

CONFIGDIR = ../../config
include $(CONFIGDIR)/java/lib.mk
