(in-package :LFEvaluator)
(push 'lf *debug-tags*)
(let ((old-context '((ONT::SPEECHACT V29594 W::SA_REQUEST :CONTENT V29593)
      (ONT::F V29595 (:* ONT::POLITENESS W::PLEASE) :OF V29593)
      (ONT::IMPRO V29596 (:* ONT::PERSON W::YOU) :CONTEXT-REL W::YOU)
      (ONT::A V29597 (:* ONT::REQUIREMENTS W::CONDITION))        
      (ONT::KIND V29598 (:* ONT::CATEGORIZATION W::DEFINE) :THEME V29597)
      (ONT::A V29599 (:* ONT::REPRESENTATIVE W::EXAMPLE))
      (ONT::KIND V29600 (:* ONT::SHOW W::SHOW) :THEME V29599)
      (ONT::F V29601 W::AND :MEMBERS (V29600 V29598))
      (ONT::F V29602 (:* ONT::SPATIAL-LOC W::BETWEEN) :VAL V29601)
      (ONT::F V29593 (:* ONT::SELECT W::CHOOSE) :THEME V29602 :AGENT V29596
         :MODS (V29595) :TMA ((W::TENSE W::PRES))))
) (new-context (list nil)))
(lf-node-to-list (lf-node-from-list (second (first old-context)) old-context) new-context)
(car new-context))

(in-package :LFEvaluator)
(push 'lf *debug-tags*)
(let ((old-context '((ONT::SPEECHACT KR::V53367 W::SA_TELL :CONTENT KR::V44527)
                   (ONT::F KR::V44527 (:* ONT::IN-RELATION W::BE) :CO-THEME
                    KR::V44766 :THEME KR::V44487 :TMA ((W::TENSE W::PRES)))
                   (ONT::PRO KR::V44487 (:* ONT::REFERENTIAL-SEM W::THIS))
                   (ONT::THE KR::V44766 (:* ONT::LIST W::LIST) :MODS
                    (KR::V44788))
                   (ONT::F KR::V44788 (:* ONT::ASSOC-WITH W::OF) :OF KR::V44766
                    :VAL KR::V50118)
                   (ONT::A KR::V50118 (W::SET-OF KR::V44806))
                   (ONT::KIND KR::V44806 (:* ONT::RESULT W::RESULT) :OF
                    KR::V49434)
                   (ONT::IMPRO KR::V49434 ONT::REFERENTIAL-SEM :FILLS-ROLE
                    (:* ONT::RESULT W::RESULT) :ROLE-VALUE-OF KR::V44806))
) (new-context (list nil)))
(lf-node-to-list (lf-node-from-list (second (first old-context)) old-context) new-context)
(car new-context))

(let ((gold '((F N4 (:* TEMPORAL-LOCATION UNDERWAY) :OF N7 :MODS (N12 N33))
 (F N12 (:* GRADE-MODIFIER WELL) :OF N4) (SPEECHACT N125 TELL :CONTENT N3)
 (BARE N7 (:* PROCESS DEVELOPMENT) :OF N17 :MODS (N63))
 (A N17 SET :MEMBERS (N18 N19) :ASSOC-WITH N20)
 (KIND N18 (:* TECHNOLOGY TECHNOLOGY)) (KIND N19 (:* TECHNOLOGY APPLICATION))
 (KIND N20 (:* SUBSTANCE ENERGY) :ASSOC-WITH N31)
 (F N33 (:* EVENT-TIME-REL BY) :VAL N32 :OF N4)
 (F N3 (:* HAVE-PROPERTY BE) :PROPERTY N4 :THEME N7)
 (KIND N31 (:* AIR-CURRENT WIND)) (THE N32 TIME-RANGE :DECADE 1930)
 (F N63 (:* RECENCY-VAL MODERN) :OF N7))
) (new-context (list nil)))
(lf-node-to-list (lf-node-from-list (second (first gold)) gold) new-context)
(car new-context))

(let ((test '((F N12 (:* GRADE-MODIFIER WELL) :OF N4) (SPEECHACT N125 TELL :CONTENT N7)
 (F N4 (:* TEMPORAL-LOCATION UNDERWAY) :MODS (N12 N33))
 (BARE N7 (:* PROCESS DEVELOPMENT) :OF N17 :MODS (N63))
 (A N17 SET :MEMBERS (N18 N19) :ASSOC-WITH N20)
 (KIND N18 (:* TECHNOLOGY TECHNOLOGY)) (KIND N19 (:* TECHNOLOGY APPLICATION))
 (BARE N20 (:* SUBSTANCE ENERGY) :ASSOC-WITH N31)
 (F N33 (:* EVENT-TIME-REL BY) :VAL N32 :OF N4) (KIND N31 (:* MOVE WIND))
 (THE N32 TIME-RANGE :DECADE 1930) (F N63 (:* RECENCY-VAL MODERN) :OF N7))
) (new-context (list nil)))
(lf-node-to-list (lf-node-from-list (second (first test)) test) new-context)
(car new-context))
