MODULE=bioagents_trips
SRCS =	__init__.py \
	kqml_dispatcher.py \
	kqml_exceptions.py \
	kqml_list.py \
	kqml_performative.py \
	kqml_reader.py \
	kqml_string.py \
	kqml_token.py \
	trips_module.py

CONFIGDIR=../config
include $(CONFIGDIR)/python/lib.mk

