#
# Makefile for TRIPS reference module
#
# Joel Tetreault, tetreaul@cs.rochester.edu, 11 Sep 2003
# $Id: Makefile,v 1.2 2007/02/22 21:12:17 ferguson Exp $
#

NAME = DiscourseContext
DEFSYS = defsys.lisp
SYSTEM = :discourse-context

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
