;;;;
;;;; File: test.lisp
;;;; Creator: George Ferguson
;;;; Created: Mon Feb 12 15:45:21 2007
;;;; Time-stamp: <Thu May 17 15:26:59 EDT 2007 swift>
;;;;

(in-package :dc)

;; This just needed to define packages in parser output unless it gets loaded in defsys
(eval-when (:load-toplevel :compile-toplevel :execute)
  (unless (find-package :w)
    (defpackage :w))
  (unless (find-package :f)
    (defpackage :f))
  (unless (find-package :ont)
    (defpackage :ont))
  )

(defun test1 ()
  (dfc:component-receive-msg dfc:*component*
    '(tell :sender parser
	   :content (new-speech-act (foo bar baz)))))

(defun test2 ()
  (dfc:component-receive-msg dfc:*component*
    '(request :sender test
	      :reply-with x123
	      :content (get-latest-word-for-lftype ONT::PERSON))))

;; a complete utterance
(defun testFULL ()
  (dfc:component-receive-msg dfc:*component*
    '(tell :sender parser
	   :CONTENT (NEW-SPEECH-ACT (UTT :TYPE W::UTT :CHANNEL DESKTOP :ROOT V27876 :TERMS ((TERM :LF (ONT::SPEECHACT V27876 W::SA_REQUEST :CONTENT V26396) :VAR V27876 :SEM NIL :INPUT (W::LET W::ME W::SHOW W::YOU W::HOW W::TO W::BUY W::A W::BOOK)) (TERM :LF (ONT::F V26396 (:* ONT::ALLOW W::LET) :EFFECT V26580 :THEME V26573 :AGENT V27864 :TMA ((W::TENSE W::PRES))) :VAR V26396 :SEM ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::ATOMIC) (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY) (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -) (F::TRAJECTORY -)) :INPUT (W::LET W::ME W::SHOW W::YOU W::HOW W::TO W::BUY W::A W::BOOK)) (TERM :LF (ONT::IMPRO V27864 ONT::PERSON :CONTEXT-REL W::*YOU*) :VAR V27864 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT) (F::MOBILITY F::SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::CONTAINER -) (F::INFORMATION -) (F::INTENTIONAL +) (F::TRAJECTORY -))) (TERM :LF (ONT::PRO V26573 (:* ONT::PERSON W::ME) :CONTEXT-REL W::ME) :VAR V26573 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT) (F::MOBILITY F::SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::CONTAINER -) (F::INFORMATION -) (F::INTENTIONAL +) (F::OBJECT-FUNCTION F::OCCUPATION) (F::TRAJECTORY -)) :INPUT (W::ME)) (TERM :LF (ONT::F V26580 (:* ONT::SHOW W::SHOW) :ADDRESSEE V26656 :THEME V27210 :AGENT V26573) :VAR V26580 :SEM ($ F::SITUATION (F::ASPECT F::ANY-ASPECT) (F::TIME-SPAN F::ANY-TIME-SPAN) (F::CAUSE F::FORCE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY) (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -) (F::TRAJECTORY -)) :INPUT (W::SHOW W::YOU W::HOW W::TO W::BUY W::A W::BOOK)) (TERM :LF (ONT::PRO V26656 (ONT::SET-OF (:* ONT::PERSON W::YOU)) :CONTEXT-REL W::YOU) :VAR V26656 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT) (F::MOBILITY F::SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::CONTAINER -) (F::INFORMATION -) (F::INTENTIONAL +) (F::OBJECT-FUNCTION F::OCCUPATION) (F::TRAJECTORY -)) :INPUT (W::YOU)) (TERM :LF (ONT::F V26777 (:* ONT::METHOD W::HOW) :OF V26830 :VAL V27210) :VAR V26777 :SEM ($ F::ABSTR-OBJ (F::MEASURE-FUNCTION -) (F::SCALE -) (F::GRADABILITY -) (F::CONTAINER -) (F::INFORMATION F::INFORMATION-CONTENT) (F::INTENTIONAL -) (F::OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION)) :INPUT (W::HOW W::TO W::BUY W::A W::BOOK)) (TERM :LF (ONT::WH-TERM V27210 ONT::METHOD :SUCHTHAT V26777 :CONTEXT-REL W::HOW) :VAR V27210 :SEM ($ NIL)) (TERM :LF (ONT::F V26830 (:* ONT::PURCHASE W::BUY) :THEME V27074) :VAR V26830 :SEM ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::ATOMIC) (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY) (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -) (F::TRAJECTORY -)) :INPUT (W::TO W::BUY W::A W::BOOK)) (TERM :LF (ONT::A V27074 (:* ONT::BOOK W::BOOK)) :VAR V27074 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::ARTIFACT) (F::FORM F::OBJECT) (F::MOBILITY F::NON-SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION F::STRIP)) (F::CONTAINER +) (F::INFORMATION F::DATA) (F::INTENTIONAL -) (F::OBJECT-FUNCTION F::REPRESENTATION) (F::TRAJECTORY +)) :INPUT (W::A W::BOOK)))))))
  )

(defun test-click ()
  (dfc:component-receive-msg dfc:*component*
    '(tell :sender parser
	   :CONTENT (NEW-SPEECH-ACT (UTT :TYPE W::UTT :CHANNEL NIL :ROOT V30387 :TERMS ((TERM :LF (ONT::SPEECHACT V30387 W::SA_REQUEST :CONTENT V30281) :VAR V30387 :SEM NIL :INPUT (W::CLICK W::ON W::BOOKS)) (TERM :LF (ONT::F V30281 (:* ONT::CLICK W::CLICK) :THEME V30361 :AGENT V30382 :TMA ((W::TENSE W::PRES))) :VAR V30281 :SEM ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::EXTENDED) (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY) (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -) (F::TRAJECTORY -)) :INPUT (W::CLICK W::ON W::BOOKS)) (TERM :LF (ONT::IMPRO V30382 ONT::PERSON :CONTEXT-REL W::*YOU*) :VAR V30382 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT) (F::MOBILITY F::SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::CONTAINER -) (F::INFORMATION -) (F::INTENTIONAL +) (F::TRAJECTORY -))) (TERM :LF (ONT::A V30361 (ONT::SET-OF (:* ONT::BOOK W::BOOK))) :VAR V30361 :SEM ($ F::PHYS-OBJ (F::ORIGIN F::ARTIFACT) (F::FORM F::OBJECT) (F::MOBILITY F::NON-SELF-MOVING) (F::GROUP -) (F::SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION F::STRIP)) (F::OBJECT-FUNCTION F::REPRESENTATION) (F::CONTAINER +) (F::INFORMATION F::DATA) (F::INTENTIONAL -) (F::TRAJECTORY +)) :INPUT (W::ON W::BOOKS))))))))

(defun testFRAG ()
  (dfc:component-receive-msg dfc:*component*
    '(tell :sender parser
	   :CONTENT (NEW-SPEECH-ACT (UTT
 :TYPE W::SA_FRAGMENT
 :CHANNEL NIL
 :ROOT V28392
 :TERMS
((TERM :LF (ONT::F V28392 (:* ONT::ALLOW W::LET) :EFFECT V28470) :VAR V28392 :SEM
  ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::ATOMIC)
   (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY)
   (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -)
   (F::TRAJECTORY -))
  :INPUT (W::LET W::TELL W::YOU W::HOW W::TO W::BUY W::A W::BOOK))
 (TERM :LF
  (ONT::F V28470 (:* ONT::STATEMENT W::TELL) :ADDRESSEE V28493 :THEME V28897)
  :VAR V28470 :SEM
  ($ F::SITUATION (F::ASPECT F::DYNAMIC) (F::TIME-SPAN F::ANY-TIME-SPAN)
   (F::CAUSE F::FORCE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY)
   (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -)
   (F::TRAJECTORY -))
  :INPUT (W::TELL W::YOU W::HOW W::TO W::BUY W::A W::BOOK))
 (TERM :LF (ONT::PRO V28493 (:* ONT::PERSON W::YOU) :CONTEXT-REL W::YOU) :VAR
  V28493 :SEM
  ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT)
   (F::MOBILITY F::SELF-MOVING) (F::GROUP -)
   (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::OBJECT-FUNCTION F::OCCUPATION)
   (F::CONTAINER -) (F::INFORMATION -) (F::INTENTIONAL +) (F::TRAJECTORY -))
  :INPUT (W::YOU))
 (TERM :LF (ONT::F V28620 (:* ONT::METHOD W::HOW) :OF V28653 :VAL V28897) :VAR
  V28620 :SEM
  ($ F::ABSTR-OBJ (F::MEASURE-FUNCTION -) (F::SCALE -)
   (F::OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION) (F::GRADABILITY -)
   (F::CONTAINER -) (F::INFORMATION F::INFORMATION-CONTENT) (F::INTENTIONAL -))
  :INPUT (W::HOW W::TO W::BUY W::A W::BOOK))
 (TERM :LF (ONT::WH-TERM V28897 ONT::METHOD :SUCHTHAT V28620 :CONTEXT-REL W::HOW)
  :VAR V28897 :SEM ($ NIL))
 (TERM :LF (ONT::F V28653 (:* ONT::PURCHASE W::BUY) :THEME V28869) :VAR V28653
  :SEM
  ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::ATOMIC)
   (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY)
   (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -)
   (F::TRAJECTORY -))
  :INPUT (W::TO W::BUY W::A W::BOOK))
 (TERM :LF (ONT::A V28869 (:* ONT::BOOK W::BOOK)) :VAR V28869 :SEM
  ($ F::PHYS-OBJ (F::ORIGIN F::ARTIFACT) (F::FORM F::OBJECT)
   (F::MOBILITY F::NON-SELF-MOVING) (F::GROUP -)
   (F::SPATIAL-ABSTRACTION (<OR> F::SPATIAL-POINT F::SPATIAL-REGION F::STRIP))
   (F::OBJECT-FUNCTION F::REPRESENTATION) (F::CONTAINER +)
   (F::INFORMATION F::DATA) (F::INTENTIONAL -) (F::TRAJECTORY +))
  :INPUT (W::A W::BOOK)))
				     )
				    )))
  )

(defun testCCA ()
  (dfc:component-receive-msg dfc:*component*
    '(tell :sender parser
	   :CONTENT (NEW-SPEECH-ACT (COMPOUND-COMMUNICATION-ACT
 :ACTS
((UTT :TYPE W::UTT :CHANNEL NIL :ROOT V31506 :TERMS
  ((TERM :LF (ONT::SPEECHACT V31506 W::SA_IDENTIFY :CONTENT V31189) :VAR V31506
    :SEM NIL :INPUT (W::ME))
   (TERM :LF (ONT::PRO V31189 (:* ONT::PERSON W::ME) :CONTEXT-REL W::ME) :VAR
    V31189 :SEM
    ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT)
     (F::MOBILITY F::SELF-MOVING) (F::GROUP -)
     (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT)
     (F::OBJECT-FUNCTION F::OCCUPATION) (F::CONTAINER -) (F::INFORMATION -)
     (F::INTENTIONAL +) (F::TRAJECTORY -))
    :INPUT (W::ME))))
 (UTT :TYPE W::UTT :CHANNEL NIL :ROOT V31569 :TERMS
  ((TERM :LF (ONT::SPEECHACT V31569 W::SA_REQUEST :CONTENT V31196) :VAR V31569
    :SEM NIL :INPUT (W::TELL W::HOW W::TO W::BUY W::A W::BOOK))
   (TERM :LF
    (ONT::F V31196 (:* ONT::STATEMENT W::TELL) :THEME V31479 :AGENT V31536 :TMA
     ((W::TENSE W::PRES)))
    :VAR V31196 :SEM
    ($ F::SITUATION (F::ASPECT F::DYNAMIC) (F::TIME-SPAN F::ANY-TIME-SPAN)
     (F::CAUSE F::FORCE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY)
     (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -)
     (F::TRAJECTORY -))
    :INPUT (W::TELL W::HOW W::TO W::BUY W::A W::BOOK))
   (TERM :LF (ONT::IMPRO V31536 ONT::PERSON :CONTEXT-REL W::*YOU*) :VAR V31536
    :SEM
    ($ F::PHYS-OBJ (F::ORIGIN F::HUMAN) (F::FORM F::SOLID-OBJECT)
     (F::MOBILITY F::SELF-MOVING) (F::GROUP -)
     (F::SPATIAL-ABSTRACTION F::SPATIAL-POINT) (F::CONTAINER -)
     (F::INFORMATION -) (F::INTENTIONAL +) (F::TRAJECTORY -)))
   (TERM :LF (ONT::F V31210 (:* ONT::METHOD W::HOW) :OF V31243 :VAL V31479) :VAR
    V31210 :SEM
    ($ F::ABSTR-OBJ (F::MEASURE-FUNCTION -) (F::SCALE -)
     (F::OBJECT-FUNCTION F::ANY-OBJECT-FUNCTION) (F::GRADABILITY -)
     (F::CONTAINER -) (F::INFORMATION F::INFORMATION-CONTENT)
     (F::INTENTIONAL -))
    :INPUT (W::HOW W::TO W::BUY W::A W::BOOK))
   (TERM :LF
    (ONT::WH-TERM V31479 ONT::METHOD :SUCHTHAT V31210 :CONTEXT-REL W::HOW) :VAR
    V31479 :SEM ($ NIL))
   (TERM :LF (ONT::F V31243 (:* ONT::PURCHASE W::BUY) :THEME V31460) :VAR V31243
    :SEM
    ($ F::SITUATION (F::ASPECT F::BOUNDED) (F::TIME-SPAN F::ATOMIC)
     (F::CAUSE F::AGENTIVE) (F::LOCATIVE -) (F::TYPE F::EVENTUALITY)
     (F::CONTAINER -) (F::INFORMATION F::MENTAL-CONSTRUCT) (F::INTENTIONAL -)
     (F::TRAJECTORY -))
    :INPUT (W::TO W::BUY W::A W::BOOK))
   (TERM :LF (ONT::A V31460 (:* ONT::BOOK W::BOOK)) :VAR V31460 :SEM
    ($ F::PHYS-OBJ (F::ORIGIN F::ARTIFACT) (F::FORM F::OBJECT)
     (F::MOBILITY F::NON-SELF-MOVING) (F::GROUP -)
     (F::SPATIAL-ABSTRACTION
      (<OR> F::SPATIAL-POINT F::SPATIAL-REGION F::STRIP))
     (F::OBJECT-FUNCTION F::REPRESENTATION) (F::CONTAINER +)
     (F::INFORMATION F::DATA) (F::INTENTIONAL -) (F::TRAJECTORY +))
    :INPUT (W::A W::BOOK)))))
				     )
				    )))
  )

(defun testBook ()
  (dfc:component-receive-msg dfc:*component*
    '(request :sender test
	      :reply-with x123
	      :content (get-latest-word-for-lftype ONT::BOOK))))


(defun testPurchase ()
  (dfc:component-receive-msg dfc:*component*
    '(request :sender test
	      :reply-with x123
	      :content (get-latest-word-for-lftype ONT::PURCHASE))))

;(defun testGM-click ()
;(gm::AKRL-TO-STRING 'ONT::P37356 '((ONT::RELN ONT::P37356 :INSTANCE-OF ONT::SELECT :OBJECT ONT::V36796) (ONT::THE ONT::V36796 :INSTANCE-OF ONT::TEXT :NAME BOOKS))))
