#
# Makefile for defcomponent
#
# George Ferguson, ferguson@cs.rochester.edu, 12 Jan 2004
# Time-stamp: <Mon Jan 12 22:54:36 EST 2004 ferguson>
#

NAME  = defcomponent
DEFSYS = defsys.lisp
SYSTEM = :defcomponent

CONFIGDIR = ../config
include $(CONFIGDIR)/lisp/lib.mk
