#
# Makefile for Lexicon Manager
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Mar 2000
# $Id: Makefile,v 1.2 2005/07/20 19:21:51 ferguson Exp $
#

NAME = WordFinder
DEFSYS = defsys.lisp
SYSTEM = :wordfinder

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
